### ISSUE TITLE
Lenovo M10 Plus G3 Bootloop

### ISSUE THREAD

**Issue by ryouze** [0x192/Universal-Android-Debloater#476]
**Your phone**: Lenovo Tab M10 Plus G3 128GB Wi-Fi (Tablet)

**Describe the issue**
Removing or disabling the package `com.lenovo.ue.device` causes a bootloop, which subsequently kicks the user into the recovery mode.

The package in question displays an annoying message on boot that asks the user to join the "User Experience Program".

This issue has been reported by other Lenovo users on XDA (see Psyl0w's post): https://forum.xda-developers.com/t/lenovo-p11-pro-user-experience-program.4393285/

I also performed a factory reset and disabled the package through ADB.

This is the result:

![lenovo](https://user-images.githubusercontent.com/98982999/209700873-d176961e-ba25-46c4-ae65-17915d1024bb.jpeg)

**You have a solution?**
Mark as unsafe for now. 

Whether removed or disabled, the tablet will bootloop.

The tablet seemed to work fine without it two weeks ago, so perhaps we can thank Lenovo for this change.

**UAD log**
Unsure if needed, it's only 1 package.

**Comment by ryouze** [comment]
I also suspected that `com.tblenovo.center` might be at fault, so I did another factory reset and removed it.

However, the tablet still seems to work just fine without it.

**Comment by SelfRef** [comment]
I had a similar issue on my Lenovo Yoga Tab 13. Disabling `com.lenovo.ue.device` caused a shutdown just after system start.

I've investigated this issue a little and noticed this happens only after connecting to WiFi. When I quickly disabled WLAN system was working correctly but just after enabling WiFi again it shutdowns.

I've also checked logcat and it turns out this issue is caused by `com.lenovo.tbengine` package because it's crashing without `com.lenovo.ue.device` so much entire OS reboots. After disabling it as well and rebooting OS it doesn't shutdown by itself.

So the solution is to disable both `com.lenovo.ue.device` and `com.lenovo.tbengine` or neither of them.

This is the interesting logcat part:
```logcat
02-27 21:35:36.802  5440  5440 D UDSEngine14: [UNKNOWN][SystemBroadcastReceiver.onReceive:48][2]Network wifi connected : true , Mobile Connected : false
02-27 21:35:36.803  1849  3496 D CompatibilityInfo: mCompatibilityFlags - 4
02-27 21:35:36.804  1849  3496 D CompatibilityInfo: applicationDensity - 240
02-27 21:35:36.804  1849  3496 D CompatibilityInfo: applicationScale - 1.0
02-27 21:35:36.804  5440  5480 E ActivityThread: Failed to find provider info for com.lenovo.ue.device.provider
02-27 21:35:36.805  5440  5480 E AndroidRuntime: FATAL EXCEPTION: Thread-2
02-27 21:35:36.805  5440  5480 E AndroidRuntime: Process: com.lenovo.tbengine, PID: 5440
02-27 21:35:36.805  5440  5480 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown URL content://com.lenovo.ue.device.provider/app
02-27 21:35:36.805  5440  5480 E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:2192)
02-27 21:35:36.805  5440  5480 E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:2157)
02-27 21:35:36.805  5440  5480 E AndroidRuntime: 	at com.lenovo.tbengine.core.util.PromptUtils.lambda$sendData$0$PromptUtils(PromptUtils.java:93)
02-27 21:35:36.805  5440  5480 E AndroidRuntime: 	at com.lenovo.tbengine.core.util.-$$Lambda$PromptUtils$Ciq_uYvVjyh8lbPyrVBSnqRFTKM.run(Unknown Source:6)
02-27 21:35:36.805  5440  5480 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
02-27 21:35:36.805  3713  3713 D GmsGcmRegister: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
02-27 21:35:36.805  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][OtaPolicy.isABUpdate:206][2]is ab update true
02-27 21:35:36.805  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][MainService.initWorkFlowTable:182][2]initWorkFlowTable isABUpdate true
02-27 21:35:36.805  1094  1094 D SurfaceFlinger: isVirtual : 0
02-27 21:35:36.805  1094  1094 D CompositionEngine: Output::prepare isVirtual : 0
02-27 21:35:36.805  1094  1094 D CompositionEngine: setColorTransform, return
02-27 21:35:36.808  1849  2147 W RescueParty: get module info error: 
02-27 21:35:36.808  1849  2147 W RescueParty: android.content.pm.PackageManager$NameNotFoundException: No module info for package: com.lenovo.tbengine
02-27 21:35:36.808  1849  2147 W RescueParty: 	at android.app.ApplicationPackageManager.getModuleInfo(ApplicationPackageManager.java:1080)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.RescueParty.needNoteCrash(RescueParty.java:783)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:582)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:562)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:8025)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:7914)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2030)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2521)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
02-27 21:35:36.808  1849  2147 W RescueParty: 	at android.os.Binder.execTransact(Binder.java:1143)
02-27 21:35:36.808  1849  2147 D RescuePartyRecorder: notePersistentAppCrash(com.lenovo.tbengine)
02-27 21:35:36.808  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][SwfABInstalling.<init>:345][2]mPowerSaveMode false
02-27 21:35:36.809  1849  2147 W ActivityManager: Process com.lenovo.tbengine has crashed too many times, killing! Reason: crashed quickly
02-27 21:35:36.810  3642  3681 D GmsServicesProvider: query caller=com.google.android.ims name=gms:phenotype:phenotype_flag:debug_bypass_phenotype value=null
02-27 21:35:36.812  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][AvatarPlugin.<init>:50][2]versionCode 8060162
02-27 21:35:36.812  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][PromptUtils.canCollectData:160][2]Lenovo YT-K606F
02-27 21:35:36.812  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][AvatarPlugin.<init>:70][2]persist.sys.backgrounddata=false
02-27 21:35:36.813  5440  5440 D UDSEngine14: [V1.1.20.230201/999000002][AvatarPlugin.<init>:77][2]persist.backgrounddata.enable=false
02-27 21:35:36.813  5440  5440 W UDSEngine14: [V1.1.20.230201/999000002][MainService.registerPlugins:235][2]AvatarPlugin report enabled!
02-27 21:35:36.813  5323  5323 I CarrierServices: [2] CarrierServicesReleaseApp.initialize:163 Initializing CarrierServices application without voice library.
02-27 21:35:36.814  1849  2147 D jxs0707 :  ActivityManagerService  handleApplicationCrash  ProcessRecord  r:  ProcessRecord{7425b7a 5440:com.lenovo.tbengine/u0a85}
02-27 21:35:36.814  1849  2147 D jxs0707 :  ActivityManagerService  handleApplicationCrash  ProcessRecord :  com.lenovo.tbengine
02-27 21:35:36.814  5440  5480 I Process : Sending signal. PID: 5440 SIG: 9
02-27 21:35:36.817  3642  3681 D GmsServicesProvider: query caller=com.google.android.ims name=gms:phenotype:phenotype_flag:debug_bypass_phenotype value=null
02-27 21:35:36.820  3642  3690 D GmsServicesProvider: query caller=com.google.android.ims name=gms:phenotype:phenotype_flag:debug_bypass_phenotype value=null
02-27 21:35:36.822  1849  2147 I ActivityManager: Process com.lenovo.tbengine (pid 5440) has died: pers PER 
02-27 21:35:36.822  1094  1094 D SurfaceFlinger: isVirtual : 0
02-27 21:35:36.822  1094  1094 D CompositionEngine: Output::prepare isVirtual : 0
02-27 21:35:36.822   891   891 I Zygote  : Process 5440 exited due to signal 9 (Killed)
02-27 21:35:36.822  1094  1094 D CompositionEngine: setColorTransform, return
02-27 21:35:36.823  3642  3681 D GmsServicesProvider: query caller=com.google.android.ims name=carrier_services_rcs_flags_enable_rcs value=null
02-27 21:35:36.823  1849  2147 E ActivityManager: Service ServiceRecord{e8e1d80 u0 com.lenovo.tbengine/.core.services.MainService} in process ProcessRecord{7425b7a 5440:com.lenovo.tbengine/u0a85} not same as in map: ServiceRecord{cc947ef u0 com.lenovo.tbengine/.core.services.MainService}
02-27 21:35:36.823  1849  2147 E ActivityManager: Service ServiceRecord{dd6de28 u0 com.lenovo.tbengine/.core.services.MainService} in process ProcessRecord{7425b7a 5440:com.lenovo.tbengine/u0a85} not same as in map: ServiceRecord{cc947ef u0 com.lenovo.tbengine/.core.services.MainService}
02-27 21:35:36.824  1849  2147 W ActivityManager: Not scheduling restart of crashed service com.lenovo.tbengine/.core.services.MainService - system is shutting down

```

**Comment by GamerClassN7** [comment]
Hello,
Is there recommended packages to remove ? on this devices 
Thank you in advance :)

**Comment by iljah** [comment]
> So the solution is to disable both com.lenovo.ue.device
> and com.lenovo.tbengine or neither of them.

Can confirm this also on Lenovo Tab M9. Doesn't matter whether from factory or after updates from today, enabling wifi causes boot loop without above solution.

**Comment by AnonymousWP** [comment]
You are all wasting your time opening Pull Requests. I've stopped doing so because the project is dead.
