### ISSUE TITLE
Can't uninstall oppo app market

### ISSUE THREAD

**Issue by abhihprajapati** [0x192/universal-android-debloater#749]
Can't uninstall oppo app market in oppo fg pro with 0.3.0 and other

**Comment by AnonymousWP** [comment]
Post some logs and explain the problem more in detail.

**Comment by MuhammedRijasKR** [comment]
I can't uninstall com.heytap.market and com.heytap.themestore from my oppo f15

**Comment by AnonymousWP** [comment]
> I can't uninstall com.heytap.market and com.heytap.themestore from my oppo f15

Post some logs man, as I said.

**Comment by cafuneandchill** [comment]
Also having the same problem with `com.heytap.market`. This happened after a recent system update (realme UI 3.0, Android 12, RMX3195_11_C.18).

Logs: [UAD_20230626.log](https://github.com/0x192/universal-android-debloater/files/11865195/UAD_20230626.log)

The relevant part:

```
2023-06-26 09:34:50 INFO  [src/gui/mod.rs:457] -----------------------------------------------------------------
2023-06-26 09:34:50 INFO  [src/gui/mod.rs:458] ANDROID_SDK: 31 | PHONE: realme RMX3195
2023-06-26 09:34:50 WARN  [src/gui/views/list.rs:142] No custom selection imported: No such file or directory (os error 2)
2023-06-26 09:37:01 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 0 com.heytap.market -> Failure [DELETE_FAILED_INTERNAL_ERROR]
2023-06-26 09:40:52 INFO  [src/gui/views/settings.rs:82] Disable mode enabled
2023-06-26 09:40:56 ERROR [src/core/utils.rs:228] [Recommended] pm clear --user 0 com.heytap.market -> 
Exception occurred while executing 'clear':
java.lang.SecurityException: PID 9241 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.heytap.market
	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:3840)
	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:2178)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:236)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25969)
	at android.os.Binder.shellCommand(Binder.java:970)
	at android.os.Binder.onTransact(Binder.java:854)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9009)
	at android.os.Binder.execTransactInternal(Binder.java:1226)
	at android.os.Binder.execTransact(Binder.java:1163)
2023-06-26 09:40:56 INFO  [src/core/utils.rs:222] [Recommended] pm disable-user --user 0 com.heytap.market -> Package com.heytap.market new state: default
2023-06-26 09:40:56 INFO  [src/core/utils.rs:222] [Recommended] am force-stop --user 0 com.heytap.market -> 
2023-06-26 09:40:59 INFO  [src/gui/mod.rs:457] -----------------------------------------------------------------
```

**Comment by Aryamanvashisht** [comment]
In Recent security patch in OPPO A15s , they introduce APP Picks which is a system app . I am not able to uninstall it using adb 
. It is taking unnecessary storage permission and we can't change it. Is there any way to uninstall it ?

**Comment by AnonymousWP** [comment]
> Also having the same problem with `com.heytap.market`. This happened after a recent system update (realme UI 3.0, Android 12, RMX3195_11_C.18).
> 
> Logs: [UAD_20230626.log](https://github.com/0x192/universal-android-debloater/files/11865195/UAD_20230626.log)
> 
> The relevant part:
> 
> ```
> 2023-06-26 09:34:50 INFO  [src/gui/mod.rs:457] -----------------------------------------------------------------
> 2023-06-26 09:34:50 INFO  [src/gui/mod.rs:458] ANDROID_SDK: 31 | PHONE: realme RMX3195
> 2023-06-26 09:34:50 WARN  [src/gui/views/list.rs:142] No custom selection imported: No such file or directory (os error 2)
> 2023-06-26 09:37:01 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 0 com.heytap.market -> Failure [DELETE_FAILED_INTERNAL_ERROR]
> 2023-06-26 09:40:52 INFO  [src/gui/views/settings.rs:82] Disable mode enabled
> 2023-06-26 09:40:56 ERROR [src/core/utils.rs:228] [Recommended] pm clear --user 0 com.heytap.market -> 
> Exception occurred while executing 'clear':
> java.lang.SecurityException: PID 9241 does not have permission android.permission.CLEAR_APP_USER_DATA to clear data of package com.heytap.market
> 	at com.android.server.am.ActivityManagerService.clearApplicationUserData(ActivityManagerService.java:3840)
> 	at com.android.server.pm.PackageManagerShellCommand.runClear(PackageManagerShellCommand.java:2178)
> 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:236)
> 	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
> 	at android.os.ShellCommand.exec(ShellCommand.java:38)
> 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25969)
> 	at android.os.Binder.shellCommand(Binder.java:970)
> 	at android.os.Binder.onTransact(Binder.java:854)
> 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
> 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9009)
> 	at android.os.Binder.execTransactInternal(Binder.java:1226)
> 	at android.os.Binder.execTransact(Binder.java:1163)
> 2023-06-26 09:40:56 INFO  [src/core/utils.rs:222] [Recommended] pm disable-user --user 0 com.heytap.market -> Package com.heytap.market new state: default
> 2023-06-26 09:40:56 INFO  [src/core/utils.rs:222] [Recommended] am force-stop --user 0 com.heytap.market -> 
> 2023-06-26 09:40:59 INFO  [src/gui/mod.rs:457] -----------------------------------------------------------------
> ```

Uninstalling doesn't work, as it's on the system partition, which is read-only for the user (0). Disabling should work as indicated by your log (which it did I believe).


> In Recent security patch in OPPO A15s , they introduce APP Picks which is a system app . I am not able to uninstall it using adb . It is taking unnecessary storage permission and we can't change it. Is there any way to uninstall it ?

No, but you can disable it (go to settings of UAD-ng).

**Comment by reda1919** [comment]
Hello 
Try this command ,it will not uninstall or disable but it will do the job
pm suspend com.....
Bye 😇😇

**Comment by shivachug** [comment]
reda1919 you saved me with suspend command.

**Comment by abhranil26** [comment]
adb shell pm suspend com.heytap.market worked for me

**Comment by reda1919** [comment]
> reda1919 you saved me with suspend command.

Glad to hear that mate.

**Comment by heyitsmethenoob** [comment]
> Hello Try this command ,it will not uninstall or disable but it will do the job pm suspend com..... Bye 😇😇

how do I put in the command ? 
or where idk I don't have the slightest clue

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/CzwbMCPEZa
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org

**Comment by reda1919** [comment]
> > Hello Try this command ,it will not uninstall or disable but it will do the job pm suspend com..... Bye 😇😇
> 
> how do I put in the command ? or where idk I don't have the slightest clue

You can use the command by using adb on your laptop or adb app on android but u need shizuku app permissions in order to get this to work on Android.
If you have never used any of this just head to youtube and search 
How to connect android to adb using laptop 
Or
How to activate adb shell using shizuku on Android Phone .
