### ISSUE TITLE
vivo phone unable to disable system app

### ISSUE THREAD

**Issue by gamernoob24** [0x192/universal-android-debloater#813]
**Describe the bug**
disabling application requires root permission

**Expected behavior**
should be disabled

**UAD log**
Upload the logfile generated by UAD.
```
2023-07-08 21:25:43 INFO  [src/gui/mod.rs:457] -----------------------------------------------------------------
2023-07-08 21:25:43 INFO  [src/gui/mod.rs:458] ANDROID_SDK: 31 | PHONE: vivo V2120
2023-07-08 21:25:43 WARN  [src/gui/views/list.rs:142] No custom selection imported: No such file or directory (os error 2)
2023-07-08 21:26:10 INFO  [src/gui/views/settings.rs:82] Disable mode enabled
2023-07-08 21:26:13 ERROR [src/core/utils.rs:228] [Unlisted] pm disable-user --user 0 com.vivo.website -> 
Exception occurred while executing 'disable-user':
java.lang.SecurityException: Cannot disable com.vivo.website no root permission
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25758)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:25610)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2231)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:257)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26553)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5266)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9025)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
2023-07-08 21:26:13 ERROR [src/core/utils.rs:228] [Unlisted] pm disable-user --user 0 com.vivo.appstore -> 
Exception occurred while executing 'disable-user':
java.lang.SecurityException: Cannot disable com.vivo.appstore no root permission
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:25758)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:25610)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2231)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:257)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26553)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5266)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:9025)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
2023-07-08 21:26:13 INFO  [src/core/utils.rs:222] [Unlisted] am force-stop --user 0 com.vivo.website -> 
2023-07-08 21:26:13 INFO  [src/core/utils.rs:222] [Unlisted] pm clear --user 0 com.vivo.website -> Success
2023-07-08 21:26:13 INFO  [src/core/utils.rs:222] [Unlisted] am force-stop --user 0 com.vivo.appstore -> 
2023-07-08 21:26:13 INFO  [src/core/utils.rs:222] [Unlisted] pm clear --user 0 com.vivo.appstore -> Success
```

**Comment by zavocc** [comment]
It appears some vivo system apps doesn't allow disabling of their apps unless your device is rooted. Which adb runs under shell user and not root with UAD
