### ISSUE TITLE
Can't enable com.android.fileexplorer 

### ISSUE THREAD

**Issue by Dimon78707** [0x192/universal-android-debloater#932]
**Describe the bug**
Can't enable com.android.fileexplorer on Redmi 8. Also I do not think I disabled it at all, but I understand I might have clicked accidentally so won't argue with this one
Log say it is enabled for user 999, but can't enable it for user 0 and that it can't change state from null to 1
Didn't notice any real difference with my phone, but not having an option to quickly turn the changes back troubles me a bit. Overall not a big deal, just wanted devs to know about a potential bug

**Expected behavior**
com.android.fileexplorer to become enabled?

**You have a solution?**
Sorry, to dumb

**UAD log**
2023-11-20 00:08:46 INFO  [src\gui\mod.rs:457] -----------------------------------------------------------------
2023-11-20 00:08:46 INFO  [src\gui\mod.rs:458] ANDROID_SDK: 29 | PHONE: Xiaomi Redmi 8
2023-11-20 00:08:47 WARN  [src\gui\views\list.rs:142] No custom selection imported: Не удается найти указанный файл. (os error 2)
2023-11-20 00:08:56 ERROR [src\core\utils.rs:228] [Advanced] pm enable --user 0 com.android.fileexplorer -> Security exception: Shell cannot change component state for com.android.fileexplorer/null to 1

java.lang.SecurityException: Shell cannot change component state for com.android.fileexplorer/null to 1
	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21969)
	at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:21850)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:1826)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:210)
	at android.os.ShellCommand.exec(ShellCommand.java:111)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22447)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4882)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4104)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
2023-11-20 00:08:56 INFO  [src\core\utils.rs:222] [Advanced] pm enable --user 999 com.android.fileexplorer -> Package com.android.fileexplorer new state: enabled

**Comment by jvirgovic** [comment]
#923
