### ISSUE TITLE
macos non rooted samsung uninstall

### ISSUE THREAD

**Issue by samascience** [0x192/universal-android-debloater#984]
**Describe the bug**
uninstall for samsung device.

**Expected behavior**
not uninstalling the list 

**You have a solution?**
not yet 

**UAD log**
2024-03-22 12:21:04 WARN  [src/gui/mod.rs:102] Trying to download remote UAD list
2024-03-22 12:21:05 WARN  [src/gui/views/list.rs:142] No custom selection imported: No such file or directory (os error 2)
2024-03-22 12:21:10 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.onetimeinitializer -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:10 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.googlequicksearchbox -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:11 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.partnersetup -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:11 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.projection.gearhead -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:11 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.printservice.recommendation -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:11 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.android.youtube -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
2024-03-22 12:21:11 ERROR [src/core/utils.rs:228] [Recommended] pm uninstall --user 150 com.google.ar.core -> 
Exception occurred while executing 'uninstall':
java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:15872 android.app.ActivityManager.handleIncomingUser:5132 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15872)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5132)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:2357)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:278)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7084)
	at android.os.Binder.shellCommand(Binder.java:1104)
	at android.os.Binder.onTransact(Binder.java:914)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7068)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 123', src/gui/views/list.rs:348:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Obegg** [comment]
If you're trying to open an issue or PR, please note that this repo has not been maintained for a while.

I have restarted development over at https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation
Please open your issues and pull requests there, as well as use those builds.

We also have a UAD-ng discord server: https://discord.gg/ygYJDf9YBn
And a UAD-ng matrix room: https://matrix.to/#/#uad-ng:matrix.org
